import comp from "/Users/a0000/Documents/project/t-blog/src/.vuepress/.temp/pages/frontend/Record-Vue.html.vue"
const data = JSON.parse("{\"path\":\"/frontend/Record-Vue.html\",\"title\":\"重学Vue3\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"重学Vue3 目录 Vue3 的源码结构 Vue的源码下载 Vue源码搭建 目录结构 运行源代码 执行第一个测试实例 debug 动手构建自己的Vue框架 尝试跟着Vue来搭建自己的包结构 安装打包器 rollup 安装 安装插件 创建rollup配置 测试 配置路径映射 探索源码 响应系统 js的程序性 令程序更加聪明 vue2 响应式采用Objec...\",\"gitInclude\":[],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://github.com/MoTangMo/t-blog/frontend/Record-Vue.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"T-Blog\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"重学Vue3\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"重学Vue3 目录 Vue3 的源码结构 Vue的源码下载 Vue源码搭建 目录结构 运行源代码 执行第一个测试实例 debug 动手构建自己的Vue框架 尝试跟着Vue来搭建自己的包结构 安装打包器 rollup 安装 安装插件 创建rollup配置 测试 配置路径映射 探索源码 响应系统 js的程序性 令程序更加聪明 vue2 响应式采用Objec...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mr.T\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"重学Vue3\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mr.T\\\",\\\"url\\\":\\\"www.tcoding.fun\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"目录\",\"slug\":\"目录\",\"link\":\"#目录\",\"children\":[]},{\"level\":2,\"title\":\"Vue3 的源码结构\",\"slug\":\"vue3-的源码结构\",\"link\":\"#vue3-的源码结构\",\"children\":[{\"level\":3,\"title\":\"Vue的源码下载\",\"slug\":\"vue的源码下载\",\"link\":\"#vue的源码下载\",\"children\":[]},{\"level\":3,\"title\":\"Vue源码搭建\",\"slug\":\"vue源码搭建\",\"link\":\"#vue源码搭建\",\"children\":[]},{\"level\":3,\"title\":\"执行第一个测试实例\",\"slug\":\"执行第一个测试实例\",\"link\":\"#执行第一个测试实例\",\"children\":[]}]},{\"level\":2,\"title\":\"动手构建自己的Vue框架\",\"slug\":\"动手构建自己的vue框架\",\"link\":\"#动手构建自己的vue框架\",\"children\":[{\"level\":3,\"title\":\"尝试跟着Vue来搭建自己的包结构\",\"slug\":\"尝试跟着vue来搭建自己的包结构\",\"link\":\"#尝试跟着vue来搭建自己的包结构\",\"children\":[]},{\"level\":3,\"title\":\"安装打包器 rollup\",\"slug\":\"安装打包器-rollup\",\"link\":\"#安装打包器-rollup\",\"children\":[]},{\"level\":3,\"title\":\"配置路径映射\",\"slug\":\"配置路径映射\",\"link\":\"#配置路径映射\",\"children\":[]}]},{\"level\":2,\"title\":\"探索源码\",\"slug\":\"探索源码\",\"link\":\"#探索源码\",\"children\":[{\"level\":3,\"title\":\"响应系统\",\"slug\":\"响应系统\",\"link\":\"#响应系统\",\"children\":[]},{\"level\":3,\"title\":\"初入reactivity模块\",\"slug\":\"初入reactivity模块\",\"link\":\"#初入reactivity模块\",\"children\":[]},{\"level\":3,\"title\":\"升级响应式模块代码\",\"slug\":\"升级响应式模块代码\",\"link\":\"#升级响应式模块代码\",\"children\":[]}]}],\"readingTime\":{\"minutes\":20.01,\"words\":6002},\"filePathRelative\":\"frontend/Record-Vue.md\",\"excerpt\":\"\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
