import comp from "E:/mynote/t-blog/src/.vuepress/.temp/pages/design-patterns/factory.html.vue"
const data = JSON.parse("{\"path\":\"/design-patterns/factory.html\",\"title\":\"工厂模式\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"工厂模式\",\"cover\":\"/assets/images/cover6.jpg\",\"icon\":\"code\",\"author\":\"Mr.T\",\"date\":\"2024-05-03T00:00:00.000Z\",\"category\":[\"设计模式\"],\"tag\":[\"Java\"],\"description\":\"工厂模式 目录 工厂模式的优势 工厂模式的劣势 代码示例 马良可不仅仅画马 工厂方法模式 拓展 📌少年应有鸿鹄志，当骑骏马他平川。 神笔马良要赏我一批骏马，令我踏平川，问我想要一批什么配置的骏马，我把我的需求跟马良哥说了，我说我要一匹黑马，时速达100km/h的黑马，他唰唰唰给我画了一匹。 回到编程的世界里，马良就是我的工厂，我需要告诉马良哥马的颜色...\",\"gitInclude\":[],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://github.com/MoTangMo/t-blog/design-patterns/factory.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"T-Blog\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"工厂模式\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"工厂模式 目录 工厂模式的优势 工厂模式的劣势 代码示例 马良可不仅仅画马 工厂方法模式 拓展 📌少年应有鸿鹄志，当骑骏马他平川。 神笔马良要赏我一批骏马，令我踏平川，问我想要一批什么配置的骏马，我把我的需求跟马良哥说了，我说我要一匹黑马，时速达100km/h的黑马，他唰唰唰给我画了一匹。 回到编程的世界里，马良就是我的工厂，我需要告诉马良哥马的颜色...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://github.com/MoTangMo/t-blog/assets/images/cover6.jpg\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://github.com/MoTangMo/t-blog/assets/images/cover6.jpg\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"工厂模式\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mr.T\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Java\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-05-03T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"工厂模式\\\",\\\"image\\\":[\\\"https://github.com/MoTangMo/t-blog/assets/images/cover6.jpg\\\"],\\\"datePublished\\\":\\\"2024-05-03T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mr.T\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"目录\",\"slug\":\"目录\",\"link\":\"#目录\",\"children\":[]},{\"level\":2,\"title\":\"工厂模式的优势\",\"slug\":\"工厂模式的优势\",\"link\":\"#工厂模式的优势\",\"children\":[]},{\"level\":2,\"title\":\"工厂模式的劣势\",\"slug\":\"工厂模式的劣势\",\"link\":\"#工厂模式的劣势\",\"children\":[]},{\"level\":2,\"title\":\"代码示例\",\"slug\":\"代码示例\",\"link\":\"#代码示例\",\"children\":[]},{\"level\":2,\"title\":\"马良可不仅仅画马\",\"slug\":\"马良可不仅仅画马\",\"link\":\"#马良可不仅仅画马\",\"children\":[{\"level\":3,\"title\":\"工厂方法模式\",\"slug\":\"工厂方法模式\",\"link\":\"#工厂方法模式\",\"children\":[]}]},{\"level\":2,\"title\":\"拓展\",\"slug\":\"拓展\",\"link\":\"#拓展\",\"children\":[]}],\"readingTime\":{\"minutes\":7.19,\"words\":2157},\"filePathRelative\":\"design-patterns/factory.md\",\"localizedDate\":\"2024年5月3日\",\"excerpt\":\"\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
